"""Index construction, persistence, and tiered rendering.

Usage
-----
    from .index import build, Index, reindex_file

    idx = build(["src", "README.md"], cfg, client=llm_client, root=project_root)
    text, tier = idx.map_for_prompt(cfg)     # what goes in every prompt
    idx = reindex_file(idx, "src/app.py", cfg)   # after an edit

An Index has two layers: a static layer from the AST/structural chunkers
(chunker.py, references.py -- exact, free), and a semantic layer of one-line
summaries generated by the LLM (this module -- slow, cached, rationed).

Rendering is tiered, because a flat map does not survive real projects.
Measured on 452KB of stdlib source (inspect/typing/tarfile/argparse, 570
units):

    flat map with summaries   ~35,500 tokens   <- larger than the usable window
    file cards (tier 0)        ~2,000 tokens
    one file's outline (t1)    ~2,400 tokens   <- fetched on demand

The map goes into *every* prompt, so tier 0 is what actually has to be cheap.
The model descends with `outline` (tier 1) and `read` (tier 2) only where it
needs detail. Small projects still get the flat map automatically, since when
it fits it is strictly more useful.

Summarisation is rationed too. Of those 570 units, 442 cleared the length
threshold, but 261 already had a docstring and 281 were methods whose class
summary plus signature says enough. Summarising only undocumented top-level
units cuts it to 76 calls: roughly 4 minutes instead of 24.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

from . import fileio
from .chunker import Chunk, chunk_source
from .chunker_ts import chunk_file_ts, LANG_BY_EXT, TS_AVAILABLE
from .llm import LLMError, ModelLoadError, estimate_tokens
from .references import chunk_reference
from .select import CODE_EXTS, PY_EXTS, REFERENCE_EXTS, Matcher, select

INDEX_DIR = ".pedacito"
CACHE_FILE = "summaries.json"
INDEX_FILE = "index.json"
BACKUP_DIR = "backups"
SESSION_DIR = "sessions"


# --------------------------------------------------------------------------
# Filesystem/workspace helpers
# --------------------------------------------------------------------------
def file_hash(path: Path) -> str:
    """Short content hash of a file's raw bytes, used to detect edits made
    outside Pedacito between runs."""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()[:16]
    except OSError:
        return ""


def state_dir(root: Path, *parts: str) -> Path:
    """Path under <root>/.pedacito/, optionally with subpath components
    appended. Everything Pedacito writes for a project lives here."""
    d = Path(root) / INDEX_DIR
    for p in parts:
        d = d / p
    return d


def infer_root(paths: list[str]) -> Path:
    """Determine the project root when --root wasn't given explicitly: the
    common ancestor of the given paths.

    Without this, running `pedacito ask ~/code/anki` from the Pedacito source
    directory would put .pedacito/ next to Pedacito's own source and render
    every file path relative to the wrong place.
    """
    resolved = []
    for p in paths:
        q = Path(p).resolve()
        resolved.append(q if q.is_dir() else q.parent)
    if not resolved:
        return Path.cwd().resolve()
    if len(resolved) == 1:
        return resolved[0]
    try:
        return Path(os.path.commonpath([str(r) for r in resolved]))
    except ValueError:
        # Different Windows drives have no common path. Fall back to the first.
        return resolved[0]


TOP_KINDS = ("function", "class", "classheader", "module")

SUMMARY_SYSTEM = (
    "You summarise Python code for a lookup index. Given one unit of code, reply with "
    "ONE sentence (two at most) describing what it does and any non-obvious assumption, "
    "side effect, or external dependency it has. Do not restate the signature. Do not "
    "list parameters. Do not use bullet points, markdown, or a preamble. Start directly "
    "with a verb."
)

FILE_SUMMARY_SYSTEM = (
    "You summarise a Python module for a lookup index. You are given the module's "
    "skeleton: its imports and the signatures of everything it defines. Reply with TWO "
    "sentences: what this module is responsible for, and what another part of the system "
    "would come here to do. Do not list the functions back. No markdown, no preamble."
)


# --------------------------------------------------------------------------
# The index itself
# --------------------------------------------------------------------------
class Index:
    """A project's chunk collection plus derived summaries, with query and
    rendering methods for the agent's tool loop and prompt construction."""

    def __init__(self, root: Path, chunks: list[Chunk],
                 file_summaries: dict[str, str] | None = None,
                 file_hashes: dict[str, str] | None = None):
        """Build an Index in memory from a flat list of chunks. Use
        `build()` or `Index.load()` rather than calling this directly in
        most cases."""
        self.root = root
        self.chunks = chunks
        self.file_summaries = file_summaries or {}
        # Content hash per file at index time. Line ranges are only meaningful
        # against the bytes they were computed from: edit a file in your editor
        # and every range below the edit shifts, so the model would read the
        # wrong function while believing it read the right one.
        self.file_hashes = file_hashes or {}
        self._by_key = {c.key: c for c in chunks}
        self._by_file: dict[str, list[Chunk]] = defaultdict(list)
        for c in chunks:
            self._by_file[c.file].append(c)
        for v in self._by_file.values():
            v.sort(key=lambda c: c.start)

    # ------------------------------------------------------------------ query
    @property
    def files(self) -> list[str]:
        """All indexed file paths (relative to root), sorted."""
        return sorted(self._by_file)

    def in_file(self, rel: str) -> list[Chunk]:
        """All chunks belonging to one file, in line order."""
        return self._by_file.get(rel, [])

    def top_level(self, rel: str) -> list[Chunk]:
        """A file's top-level definitions: what a file card names (top-level
        defs and classes, never methods)."""
        return [c for c in self.in_file(rel)
                if c.kind in ("function", "class", "classheader")]

    def stale(self) -> tuple[list[str], list[str]]:
        """Return (changed, missing): files whose content hash no longer
        matches what was indexed, and files that have been deleted since."""
        changed, missing = [], []
        for rel in self.files:
            p = self.root / rel
            if not p.exists():
                missing.append(rel)
                continue
            known = self.file_hashes.get(rel)
            if known and file_hash(p) != known:
                changed.append(rel)
        return changed, missing

    def forget(self, rel: str) -> None:
        """Remove a file entirely from the index (its chunks, summary, and
        hash), used when a file has been deleted."""
        self.chunks = [c for c in self.chunks if c.file != rel]
        self._by_file.pop(rel, None)
        self.file_summaries.pop(rel, None)
        self.file_hashes.pop(rel, None)

    def is_reference(self, rel: str) -> bool:
        """Whether a file was indexed structurally (non-Python) rather than
        as parsed code."""
        return all(c.kind == "reference" for c in self.in_file(rel))

    @property
    def code_files(self) -> list[str]:
        """Indexed files that are Python source, sorted."""
        return [f for f in self.files if not self.is_reference(f)]

    @property
    def reference_files(self) -> list[str]:
        """Indexed files that are non-Python reference material, sorted."""
        return [f for f in self.files if self.is_reference(f)]

    def resolve_file(self, name: str) -> str | None:
        """Resolve a user- or model-typed file reference ('db.py',
        'src/db.py', 'src\\db.py', or the exact indexed path) to the exact
        path stored in the index, or None if no match."""
        n = fileio.normalise_rel(name)
        if not n:
            return None
        for f in self.files:
            if f == n:
                return f
        for f in self.files:
            if f.endswith("/" + n) or Path(f).name == n:
                return f
        return None

    def find_symbol(self, symbol: str) -> list[Chunk]:
        """Find chunk(s) matching a symbol name: exact qualname match first,
        then case-insensitive qualname/suffix match, then (for methods of a
        class that was indexed whole) the owning class."""
        s = symbol.strip()
        hits = [c for c in self.chunks if c.qualname == s]
        if hits:
            return hits
        low = s.lower()
        hits = [c for c in self.chunks
                if c.qualname.lower() == low or c.qualname.lower().endswith("." + low)]
        if hits:
            return hits
        # Small classes are indexed whole, so a bare method name won't match a
        # qualname. Fall back to the class that declares it.
        base = s.split(".")[-1]
        return [c for c in self.chunks if base in c.members]

    def callers_of(self, symbol: str) -> list[Chunk]:
        """Chunks whose call list contains this symbol's bare name. An
        approximate cross-reference (names, not resolved bindings)."""
        base = symbol.split(".")[-1]
        return [c for c in self.chunks if base in c.calls]

    # ------------------------------------------------------ tier 0: file cards
    def render_files(self, line_ranges: bool = True, max_names: int = 60) -> str:
        """Render the always-resident tier-0 map: one card per file naming
        what it is, what it imports, and what it defines, with line ranges
        attached to the names so the model can often go straight to `read`
        without an `outline` round trip -- worth the extra characters at
        ~25 tok/s."""
        out: list[str] = []
        for f in self.code_files + self.reference_files:
            units = self.in_file(f)
            if self.is_reference(f):
                out.append(self._reference_card(f, units, line_ranges))
                continue
            top = self.top_level(f)
            nlines = max((c.end for c in units), default=0)
            imports = sorted({i.split(".")[0].lstrip(".") for c in units for i in c.imports})
            card = [f"### {f}  ({nlines} lines, {len(units)} units)"]
            if imports:
                card.append(f"  imports: {', '.join(imports[:14])}")
            summary = self.file_summaries.get(f)
            if summary:
                card.append(f"  {summary}")
            if top:
                shown, hidden = _cap(top, max_names)
                names = []
                for c in shown:
                    end = c.scope_end or c.end   # full class span, not the header
                    names.append(f"{c.qualname}:L{c.start}-{end}" if line_ranges
                                 else c.qualname)
                extra = f" (+{hidden} hidden; use outline)" if hidden else ""
                card.append(f"  defines: {', '.join(names)}{extra}")
            out.append("\n".join(card))
        return "\n\n".join(out)

    def _reference_card(self, f: str, units: list[Chunk], line_ranges: bool) -> str:
        """Render a tier-0 card for a non-code file: shape, not contents.
        The model needs to know a config or data file exists and roughly
        what is in it, then can `read` or `grep` it on demand."""
        nlines = max((c.end for c in units), default=0)
        card = [f"### {f}  ({nlines} lines, reference)"]
        summary = self.file_summaries.get(f)
        if summary:
            card.append(f"  {summary}")
        for c in units[:20]:
            bit = f"  {c.signature}"
            if line_ranges and c.end:
                bit += f"  L{c.start}-{c.end}"
            if c.docline:
                bit += f"\n      {c.docline}"
            card.append(bit)
        if len(units) > 20:
            card.append(f"  (+{len(units) - 20} more sections; use outline)")
        return "\n".join(card)

    # -------------------------------------------------- tier 1: per-file detail
    def render_outline(self, rel: str, header: bool = True) -> str:
        """Render every unit in one file with signature, line range, and
        summary/docline: the `outline` tool's output, and also used to build
        the flat map when a project is small enough for one."""
        rows: list[str] = [f"### {rel}"] if header else []
        for c in self.in_file(rel):
            loc = f"L{c.start}-{c.end}"
            if c.kind == "module":
                label = "module preamble" if c.qualname == "module" else "top-level code"
                imps = ", ".join(c.imports[:12])
                head = f"  {loc:<12} {label}" + (f"  [imports: {imps}]" if imps else "")
            elif c.kind == "classheader":
                span = f"L{c.start}-{c.scope_end or c.end}"
                head = (f"  {span:<12} {c.signature}  "
                        f"(header {c.start}-{c.end}; methods below)")
            else:
                indent = "    " if c.kind == "method" else "  "
                head = f"{indent}{loc:<12} {c.signature}"
                if c.decorators:
                    head += "  " + " ".join(c.decorators[:2])
            text = c.summary or c.docline
            if text:
                head += f"\n{' ' * 16}-- {text}"
            if c.kind == "class" and c.members:
                head += f"\n{' ' * 16}   methods: {', '.join(c.members)}"
            rows.append(head)
        return "\n".join(rows)

    def render(self, max_chars: int = 10 ** 9) -> str:
        """Render every unit in every file: the flat map, used only when a
        project is small enough to fit the token budget (see
        `map_for_prompt`)."""
        out: list[str] = []
        # Code first, reference material after, matching the card renderer: the
        # model should meet the project's code before its config.
        for f in self.code_files + self.reference_files:
            out.append(f"### {f}")
            out.append(self.render_outline(f, header=False))
            out.append("")
        s = "\n".join(out)
        if len(s) > max_chars:
            s = s[:max_chars] + "\n... [truncated; use outline or grep for the rest]"
        return s

    # --------------------------------------------------------- tier selection
    def map_for_prompt(self, cfg) -> tuple[str, str]:
        """Choose and render the map for a prompt: the flat map if it fits
        within cfg.flat_map_token_budget, otherwise the tier-0 file cards.
        Returns (map_text, tier_name)."""
        flat = self.render()
        if estimate_tokens(flat) <= cfg.flat_map_token_budget:
            return flat, "flat"
        return self.render_files(line_ranges=cfg.file_card_line_ranges), "cards"

    # ------------------------------------------------------------- persistence
    def save(self) -> Path:
        """Write the index (chunks, file summaries, file hashes) to
        .pedacito/index.json under the project root."""
        d = self.root / INDEX_DIR
        d.mkdir(exist_ok=True)
        payload = {
            "root": str(self.root),
            "file_summaries": self.file_summaries,
            "file_hashes": self.file_hashes,
            "chunks": [c.to_record() for c in self.chunks],
        }
        p = d / INDEX_FILE
        p.write_text(json.dumps(payload, indent=1))
        return p

    @classmethod
    def load(cls, root: Path) -> "Index | None":
        """Load a previously saved index from .pedacito/index.json under
        `root`, re-reading each chunk's source text from disk (except
        reference chunks, whose small preview is kept as-is). Returns None
        if no index has been saved yet."""
        p = root / INDEX_DIR / INDEX_FILE
        if not p.exists():
            return None
        data = json.loads(p.read_text())
        chunks = [Chunk(**rec) for rec in data["chunks"]]
        cache: dict[str, list[str]] = {}
        for c in chunks:
            # Reference chunks deliberately keep only a small preview as source.
            # Rehydrating them from their line range would pull a multi-megabyte
            # CSV into memory on every load, and nothing downstream wants it:
            # they are never summarised and never used as an edit anchor.
            if c.kind == "reference":
                continue
            if c.file not in cache:
                fp = root / c.file
                cache[c.file] = fileio.read_lines(fp) if fp.exists() else []
            lines = cache[c.file]
            if lines:
                c.source = "\n".join(lines[c.start - 1 : c.end])
        return cls(root, chunks, data.get("file_summaries", {}),
                   data.get("file_hashes", {}))


# --------------------------------------------------------------------------
# Rendering helpers
# --------------------------------------------------------------------------
def _cap(units: list[Chunk], max_names: int) -> tuple[list[Chunk], int]:
    """Fit a file's definitions into a card's name limit. When over the cap,
    drop private (underscore-prefixed) helpers before public ones --
    truncating in line order would hide a module's public API behind its
    leading private utilities."""
    if len(units) <= max_names:
        return units, 0
    public = [c for c in units if not c.qualname.startswith("_")]
    if len(public) <= max_names:
        return public, len(units) - len(public)
    return public[:max_names], len(units) - max_names


# --------------------------------------------------------------------------
# Summary cache (keyed by chunk content hash, records which model wrote it)
# --------------------------------------------------------------------------
def _entry(value) -> tuple[str, str]:
    """Read one cache entry, accepting both the legacy plain-string form and
    the current {"text", "model"} dict form. Returns (text, model_id)."""
    if isinstance(value, dict):
        return value.get("text", ""), value.get("model", "?")
    return value or "", "?"


def _put(cache: dict, key: str, text: str, model: str) -> None:
    """Write one cache entry, recording which model produced the summary so
    a later `pedacito config` / index run can tell whose words are being read."""
    cache[key] = {"text": text, "model": model}


def cache_models(cache: dict) -> dict[str, int]:
    """Count cache entries by which model produced them, for reporting when
    an index is being reused across a model switch."""
    counts: dict[str, int] = {}
    for v in cache.values():
        _, m = _entry(v)
        counts[m] = counts.get(m, 0) + 1
    return counts


def _load_cache(root: Path) -> dict:
    """Load the persisted summary cache from .pedacito/summaries.json."""
    p = root / INDEX_DIR / CACHE_FILE
    if p.exists():
        try:
            return json.loads(p.read_text())
        except json.JSONDecodeError:
            return {}
    return {}


def _save_cache(root: Path, cache: dict) -> None:
    """Persist the summary cache to .pedacito/summaries.json."""
    d = root / INDEX_DIR
    d.mkdir(exist_ok=True)
    (d / CACHE_FILE).write_text(json.dumps(cache, indent=1))


# --------------------------------------------------------------------------
# Summarisation rationing
# --------------------------------------------------------------------------
def needs_summary(c: Chunk, cfg) -> bool:
    """Decide whether a chunk is worth spending an LLM call to summarise,
    applying the rationing rule in cost order: too short, a method covered
    by its class, or already documented are all excluded by default."""
    if c.kind == "reference":
        return False   # shape is already extracted; prose adds nothing
    if c.nlines < cfg.min_lines_to_summarise:
        return False
    if c.kind not in TOP_KINDS and not cfg.summarise_methods:
        return False
    if c.docline and not cfg.summarise_documented:
        return False
    return True


def summary_plan(idx: "Index", cfg) -> dict:
    """Compute what indexing would cost without spending it: counts of
    eligible/skipped/to-summarise chunks and files. Used by `pedacito cost`."""
    eligible = [c for c in idx.chunks if c.nlines >= cfg.min_lines_to_summarise]
    todo = [c for c in idx.chunks if needs_summary(c, cfg)]
    by_doc = sum(1 for c in eligible if c.docline and not cfg.summarise_documented)
    by_kind = sum(1 for c in eligible
                  if c.kind not in TOP_KINDS and not cfg.summarise_methods)
    files = idx.files if cfg.summarise_references else idx.code_files
    return {
        "units": len(idx.chunks),
        "eligible": len(eligible),
        "skipped_documented": by_doc,
        "skipped_methods": by_kind,
        "skipped_references": sum(1 for c in idx.chunks if c.kind == "reference"),
        "unit_calls": len(todo),
        "file_calls": len(files),
    }


def _skeleton(idx: Index, rel: str, limit: int = 4000) -> str:
    """Build a compact stand-in for a file when summarising it: its imports
    and every top-level signature (with existing docstrings and class
    members). Fits in a prompt even when the file itself (e.g. 2,700 lines)
    would not."""
    units = idx.in_file(rel)
    if idx.is_reference(rel):
        rows = [f"file: {rel}"] + [f"  {c.signature} {c.docline}".rstrip() for c in units[:40]]
        return "\n".join(rows)[:limit]
    imports = sorted({i for c in units for i in c.imports})
    lines = [f"module: {rel}", f"imports: {', '.join(imports[:40])}"]
    for c in units:
        if c.kind in ("function", "class", "classheader"):
            line = f"  {c.signature or c.qualname}"
            if c.docline:
                line += f"  # {c.docline[:100]}"
            if c.members:
                line += f"  [methods: {', '.join(c.members[:20])}]"
            lines.append(line)
    return "\n".join(lines)[:limit]


# --------------------------------------------------------------------------
# Summarisation batch control
# --------------------------------------------------------------------------
class _Breaker:
    """Aborts an indexing batch after repeated consecutive failures.

    A model that cannot load fails identically for every chunk. Warning 55
    times and then writing an index of blank summaries is worse than
    stopping at the third failure and saying why.
    """

    def __init__(self, limit: int):
        """Track failures against `limit` consecutive occurrences."""
        self.limit = limit
        self.consecutive = 0
        self.total = 0

    def ok(self) -> None:
        """Reset the consecutive-failure counter after a successful call."""
        self.consecutive = 0

    def fail(self, label: str, err: Exception) -> None:
        """Record one failure; raises SystemExit if the batch should stop
        (a model-load error, or `limit` consecutive failures reached)."""
        self.consecutive += 1
        self.total += 1
        print(f"[warn] summary failed for {label}: {err}", file=sys.stderr)
        if isinstance(err, ModelLoadError) or self.consecutive >= self.limit:
            raise SystemExit(
                f"\nStopping: {self.consecutive} summaries in a row failed.\n"
                f"{err}\n\n"
                "Progress so far is cached, so fixing the problem and re-running\n"
                "`pedacito index` will resume rather than start over."
            )


def _ask(client, cfg, system: str, prompt: str, label: str,
         breaker: "_Breaker | None" = None) -> str:
    """Request one summary from the model, truncating to 400 chars. Reports
    failures to `breaker` if given (may raise SystemExit), otherwise just
    warns and returns an empty string."""
    try:
        s = client.chat(
            [{"role": "system", "content": system}, {"role": "user", "content": prompt}],
            max_tokens=cfg.max_tokens_summary,
        ).strip().replace("\n", " ")
    except LLMError as e:
        if breaker is not None:
            breaker.fail(label, e)
        else:
            print(f"[warn] summary failed for {label}: {e}", file=sys.stderr)
        return ""
    if breaker is not None:
        breaker.ok()
    if len(s) > 400:
        s = s[:400].rsplit(" ", 1)[0] + "..."
    return s


# --------------------------------------------------------------------------
# Per-file chunker dispatch
# --------------------------------------------------------------------------
def _chunk_file(rel: str, path: Path, cfg) -> list[Chunk]:
    """Chunk one selected file with whichever chunker matches its extension:
    AST-based for Python (exact), tree-sitter for JS/TS/TSX when the
    optional dependency is installed (also exact), or structural
    reference-chunking otherwise.

    A JS/TS file with tree-sitter unavailable falls back to
    reference-chunking rather than being dropped -- the file still gets a
    file-card entry and is still reachable by `read`/`grep`, just without a
    symbol-level map, exactly the degraded-but-present treatment the README
    describes for any language the project doesn't parse into symbols.
    """
    suffix = path.suffix.lower()
    if suffix in PY_EXTS:
        src = fileio.read_text(path)
        return chunk_source(rel, src, cfg.class_split_lines)
    if suffix in LANG_BY_EXT:
        if TS_AVAILABLE:
            src = fileio.read_text(path)
            return chunk_file_ts(rel, src, suffix, cfg.class_split_lines)
        return chunk_reference(rel, path, cfg.max_reference_bytes)
    return chunk_reference(rel, path, cfg.max_reference_bytes)


# --------------------------------------------------------------------------
# Public API: building and refreshing the index
# --------------------------------------------------------------------------
def build(paths: list[str], cfg, client=None, root: Path | None = None,
          summarise: bool = True, verbose: bool = True,
          matcher: Matcher | None = None, resummarise: bool = False) -> Index:
    """Build a full Index from scratch: select files, chunk each one
    (AST-based for Python, tree-sitter for JS/TS, structural for other
    reference files), and optionally
    generate LLM summaries (file summaries first, then rationed unit
    summaries), consulting and updating the on-disk summary cache
    throughout. Saves the result to .pedacito/index.json before returning.

    If `client` is None or `summarise` is False, only the static index is
    built (no LLM calls) -- used for `pedacito map`/`pedacito files`/`pedacito cost`.
    """
    root = (root or Path.cwd()).resolve()
    matcher = matcher if matcher is not None else Matcher.from_files(root)

    exts = set(CODE_EXTS)
    if cfg.include_references:
        exts |= set(REFERENCE_EXTS)
    exts |= {e if e.startswith(".") else "." + e for e in cfg.extra_extensions}

    files = select(paths, root, matcher, exts)
    if not files:
        raise SystemExit(
            "Nothing to index in: " + ", ".join(paths) +
            "\nEverything matched an ignore rule, or no files had an indexed "
            "extension. Try `pedacito files` to see what was considered.")

    chunks: list[Chunk] = []
    for f in files:
        try:
            rel = f.resolve().relative_to(root).as_posix()
        except ValueError:
            rel = f.name
        try:
            chunks.extend(_chunk_file(rel, f, cfg))
        except SyntaxError as e:
            print(f"[skip] {rel}: syntax error line {e.lineno}", file=sys.stderr)

    idx = Index(root, chunks)
    for f in files:
        try:
            rel = f.resolve().relative_to(root).as_posix()
        except ValueError:
            rel = f.name
        idx.file_hashes[rel] = file_hash(f)
    if not (summarise and client is not None):
        idx.save()
        return idx

    cache = {} if resummarise else _load_cache(root)
    for c in chunks:
        if c.sha in cache:
            c.summary = _entry(cache[c.sha])[0]

    if verbose and cache:
        counts = cache_models(cache)
        foreign = {m: n for m, n in counts.items() if m not in ("?", cfg.model)}
        if foreign:
            listed = ", ".join(f"{n} from {m}" for m, n in sorted(foreign.items()))
            print(f"  reusing cached summaries ({listed}); "
                  f"--resummarise to regenerate with {cfg.model}", file=sys.stderr)

    breaker = _Breaker(cfg.max_consecutive_failures)

    # Prove the model can actually generate before committing to a long batch.
    if verbose:
        print("  checking the model responds...", file=sys.stderr)
    try:
        client.warmup()
    except LLMError as e:
        _save_cache(root, cache)
        raise SystemExit(f"\n{e}\n\nNothing was indexed.")

    # --- file summaries first: they carry the tier-0 map, so they matter most
    for rel in idx.files:
        if idx.is_reference(rel) and not cfg.summarise_references:
            continue
        skel = _skeleton(idx, rel)
        key = "file:" + hashlib.sha256(skel.encode()).hexdigest()[:16]
        if key in cache:
            idx.file_summaries[rel] = _entry(cache[key])[0]
            continue
        if verbose:
            print(f"  [file] {rel}", file=sys.stderr)
        s = _ask(client, cfg, FILE_SUMMARY_SYSTEM, skel, rel, breaker)
        if s:
            idx.file_summaries[rel] = s
            _put(cache, key, s, cfg.model)
    _save_cache(root, cache)

    # --- unit summaries, rationed
    todo = [c for c in chunks if not c.summary and needs_summary(c, cfg)]
    if verbose:
        plan = summary_plan(idx, cfg)
        print(f"  {len(todo)} units to summarise "
              f"({plan['skipped_documented']} have docstrings, "
              f"{plan['skipped_methods']} are methods covered by their class)",
              file=sys.stderr)

    for i, c in enumerate(todo, 1):
        if verbose:
            print(f"  [{i}/{len(todo)}] {c.key}", file=sys.stderr)
        prompt = (f"File: {c.file}\nUnit: {c.qualname} ({c.kind}), "
                  f"lines {c.start}-{c.end}\n\n"
                  f"```python\n{c.source[:cfg.max_chunk_chars]}\n```")
        try:
            s = _ask(client, cfg, SUMMARY_SYSTEM, prompt, c.key, breaker)
        except SystemExit:
            _save_cache(root, cache)   # keep what we already paid for
            idx.save()
            raise
        if s:
            c.summary = s
            _put(cache, c.sha, s, cfg.model)
        if i % 10 == 0:
            _save_cache(root, cache)
    _save_cache(root, cache)

    idx.save()
    return idx


def reindex_file(index: Index, rel: str, cfg) -> Index:
    """Re-chunk a single file after it has changed (either by Pedacito's own
    edit or externally) and return an updated Index. Summaries carry over by
    content hash, so untouched functions keep theirs and only genuinely
    changed ones lose theirs."""
    root = index.root
    kept = [c for c in index.chunks if c.file != rel]
    try:
        new = _chunk_file(rel, root / rel, cfg)
    except (SyntaxError, OSError) as e:
        print(f"[warn] {rel} could not be re-indexed ({e}); index left stale",
              file=sys.stderr)
        return index
    cache = _load_cache(root)
    for c in new:
        c.summary = _entry(cache[c.sha])[0] if c.sha in cache else ""
    merged = Index(root, kept + new, dict(index.file_summaries),
                   dict(index.file_hashes))
    merged.file_hashes[rel] = file_hash(root / rel)
    merged.save()
    return merged
